//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int IDOrder { get; set; }
        public int IdPiano { get; set; }
        public int IdUser { get; set; }
        public System.DateTime SaleDate { get; set; }
    
        public virtual Piano Piano { get; set; }
        public virtual Users Users { get; set; }
    }
}
